wedapp/Androidapp/urls.py
from django.contrib import admin
from Androidapp import views
from django.urls import path
from .views import AndroidAppListCreateView, UserTaskSubmitView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

app_name='Androidapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('adminregistration/',views.admin_registration,name='adminregistration'),
    path('adminlogin/', views.admin_login, name='admin_login'),
    path('addapp', views.add_app,name='add_app'),
    path('appview/<int:app_id>', views.display_android_app, name='view'),
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('userview', views.user_view, name='user_view'),
    path('app/<int:p>',views.app_view,name='appview'),




    path('api/admin/apps/', AndroidAppListCreateView.as_view(), name='android-app-list-create'),
    # path('api/user/profile/', UserProfileView.as_view(), name='user-profile'),
    path('api/user/tasks/<int:app_id>/submit/', UserTaskSubmitView.as_view(), name='user-task-submit'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wedapp/Webapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Androidapp.urls')),
]

wedapp/templates/Userlogin.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

wedapp/templates/admin_exists_popup.html
<!-- admin_exists_popup.html -->

{% load static %}



{% block content %}
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Admin Exists</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>An admin already exists.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function () {
        $('.modal').modal('show');
    });
</script>
{% endblock %}

wedapp/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Login</title>
</head>
<body>
    <h1>Admin Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

wedapp/templates/admin_view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/b.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:ital,wght@1,600&display=swap">
</head>
<body>
<div class="container">
    <form>
        <img src="{{ android_app.image.url }}" alt="..." height="300">
        <div class="row">
            <div class="col">
                <label for="app_name">App name:</label>
                <input type="text" class="form-control" id="app_name" placeholder="App name" value="{{ android_app.name }}">
            </div>
            <div class="col">
                <label for="app_link">Link:</label>
                <input type="text" class="form-control" id="app_link" placeholder="Link" value="{{ android_app.link }}">
            </div>
             <div class="row">
            <div class="col">
                <label for="app_name">Category:</label>
                <input type="text" class="form-control" id="category" placeholder="Category" value="{{ android_app.category }}">
            </div>
            <div class="col">
                <label for="app_link">Subcategory:</label>
                <input type="text" class="form-control" id="subcategory" placeholder="Subcategory" value="{{ android_app.subcategory }}">
            </div>
        </div>
        <br>
    </form>
    <br><br>

    <div class="center-button">
        <a class="btn btn-info" type="submit">{{ android_app.points }} Points</a><br><br>
        <a class="btn btn-warning" type="submit">SUBMIT</a>
    </div>
</div>
</body>
</html>

wedapp/templates/app_adding.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:ital,wght@1,600&display=swap">
</head>
<body>
<h3 style="text-align:center;">Hello Admin</h3>
<!DOCTYPE html>
<html>
<head>
    <title>Add Android App</title>
</head>
<body>
    <h2>Add a New Android App</h2>
    <form action="{% url 'Androidapp:add_app' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add App</button>
         <p class="success">{{ success_message }}</p>
    </form>
</body>
</html>


</body>
</html>

wedapp/templates/app_view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:ital,wght@1,600&display=swap">
</head>
<body>
<div class="container mt-4">
    <h1>Welcome, {{ request.user.username }}</h1>
    <h2>Upload Screenshot for App: {{ app.name }}</h2>
</div>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <h4>App Logo</h4>
            <img src="{{ i.image.url }}" alt="App Logo" class="img-fluid">
        </div>
        <div class="col-md-6">
            <h4>Upload Screenshot</h4>
            <div class="dropzone">
                <div class="fallback">
                    <input name="file" type="file" />
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Include Dropzone.js library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.js"></script>
<script>
    // Initialize Dropzone
    Dropzone.options.myDropzone = {
        paramName: "file", // The name that will be used to transfer the file
        maxFilesize: 2, // MB
        acceptedFiles: ".png, .jpg, .jpeg",
        dictDefaultMessage: "Drag and drop files here or click to upload"
    };
</script>

</body>
</html>

wedapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
     <link rel="stylesheet" href="{% static 'CSS/a.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:ital,wght@1,600&display=swap">


<style>
body {
        width: 100%;
        height: 100vh;
        background: linear-gradient(to bottom, #f9f9f9, #ddd); /* Gradient from white to light gray */
}
.menu{
width:400px;
hieght:70px;
 }



</style>
</head>
<body>
<header>
<div class="menu">
  <form class="container-fluid justify-content-start">
    <a class="btn btn-outline-success me-2" type="button" href="{% url 'Androidapp:adminregistration' %}"> ADMIN SIGN-UP</a>
      <a class="btn btn-outline-success me-2" type="button" href="{% url 'Androidapp:admin_login' %}"> ADMIN LOGIN</a>
    <a class="btn btn-outline-success me-2" type="button" href="{% url 'Androidapp:register' %}"> USER SIGN-UP</a>
      <a class="btn btn-outline-success me-2" type="button" href="{% url 'Androidapp:login' %}"> USER LOGIN</a>
  </form>
</div>
</header>
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ZJpNb90tj1aX3iZv7vG5j13KSOmB8YVI3pod27dgfF/rSP7cN1VWW6d+KXTRIiS" crossorigin="anonymous"></script>
</body>
</html>

wedapp/templates/createadmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <h1>Create Admin</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Admin">
    </form>
</body>
</html>

wedapp/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
</head>
<body>
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>

wedapp/templates/user_view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:ital,wght@1,600&display=swap">
</head>
<body>
<div class="container mt-4">
    <h1>Welcome, {{ request.user.username }}</h1>
    <h2>Android Apps Added by You:</h2>
</div>

<div class="container mt-4">
    {% for i in app %}
    <div class="row mb-3">
        <div class="col-md-2">
            <img src="{{ i.image.url }}" alt="App Image" class="img-fluid">
        </div>
        <div class="col-md-7">
            <h5><a href="#" class="profile-link">{{ i.name }}</a></h5>
            <p>{{ i.link }}</p>
        </div>
        <div class="col-md-3">
            <a class="btn btn-outline-success me-2" type="button" href="{% url 'Androidapp:appview' i.id %}">{{i.points}} POINTS</a>
        </div>
    </div>
    {% endfor %}
</div>

</body>
</html>